version: "3.1"
services:
    web-server:
        build:
          context: ./www
          dockerfile: Dockerfile
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    db:
        image: mariadb:latest
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        depends_on:
          - db 
volumes:
    persistent: